name: 'Creating documentation in md format'
description: 'no description'
inputs:
  inputdir:
    description: 'directory with files'
    requred: true
    default: 'test'
  mdpath:
    description: 'where will be md file'
    requred: true
    default: './docs/'
  mdname:
    description: 'name md file'
    requred: true
    default: 'README.md'
outputs:
  mdfile: 
    description: "md file"
    value: ${{ steps.mdfile.outputs.mdfile }}
runs:
  using: "composite"
  steps: 

    - name: install doxygen
      run: sudo apt install doxygen -y
      shell: bash

    - name: instaill doxygen2markdown
      run: npm i -g doxygen2markdown
      shell: bash

    - name: Make xml files
      run: |
        mkdir -p ./doxygen_act/
        cp ${{ inputs.inputdir }}/* ./doxygen_act/
        cp ${{ github.action_path }}/Doxyfile ./doxygen_act/
        pushd ./doxygen_act/
        doxygen Doxyfile
        popd
      shell: bash

    - name: Make md file
      id: mdfile
      run: |
        pushd ./doxygen_act/
        mkdir -p ./result/
        doxygen2markdown -d ./xml/ -o ./result/
        rm -R ./xml/
        cat ./result/*.md >> ${{ inputs.mdname }}
        rm -R ./result/
        popd
        mkdir -p ${{ inputs.mdpath }}
        mv ./doxygen_act/${{ inputs.mdname }} ./${{ inputs.mdpath }}/${{ inputs.mdname }}
        rm -R ./doxygen_act/
        MDFILE=./${{ inputs.mdpath }}/${{inputs.mdname}}
        echo "::set-output name=mdfile::$(echo $MDFILE)"
      shell: bash
