name: Test

on:
  push:
    branches:
      - main

jobs:
  makemd:
    name: Make MD
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
      
    - name: Make md file
      uses: Jnqa/documentation2md@v1
      id: makemd
      with:
        inputdir: test
        mdpath: docs
        mdname: messages.md

    - name: echo TEST
      run: |
        echo ${{ steps.makemd.outputs.mdfile }} 
        cat ${{ steps.makemd.outputs.mdfile }} 

    - name: Create pull request
      uses: peter-evans/create-pull-request@v3
      with:
        branch: documentation
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        commit-message: add documentation
        title: 🆕 New doc file ${{ steps.makemd.outputs.mdfile }}